[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { git = "https://github.com/evenfurther/aoc" }
eyre = "0.6.12"

[build-dependencies]
aoc-build = { git = "https://github.com/evenfurther/aoc" }
